### ISSUE TITLE
AppCrash after choosing a new directory via Movie composer

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#130]
**Describe the bug**
After trying to choose a new directory from the MovieComposer window (NOT directly in the Frame directory window - that one works), the app crashes

**Indicate the dataset**
Example->0200nm

**To Reproduce**
1. Load data
2. Set two example widgets (I used matplotlib and 3D arrows)
3. Go to MovieComposer window and select a new directory when asked (choose a new one and not the same)
4. The app crashes

**Screenshots**
https://imgur.com/W0tN4UC

**Desktop (please complete the following information):**
Windows 7

**Comment by LemurPwned** [comment]
This is due to the fact that Windows do not natively support ffmpeg which is used to compose videos.
However, a Windows distribution of that codec can be installed from this site for example:
https://www.ffmpeg.org/download.html

Please let me know if that helps.
Nevertheless, I will add the pop-ip message window to inform the user about the need to install ffmpeg rather than just crash the application.

**Comment by JakubChecinski** [comment]
Before downloading:
No pop-up message for me, but I got the correct error message about FFmpeg in the console, so I guess it's fine. 

I will post message tomorrow about what happens after downloading - the installation requires resetting the system and I don't want to do that right now.

**Comment by LemurPwned** [comment]
ok great :) I will make it into Pop-up

**Comment by JakubChecinski** [comment]
Confirmed, it works correctly with ffmpeg installed.

**Comment by LemurPwned** [comment]
Ok, then I'm closing this issue.
