### ISSUE TITLE
Disabling RGB colors in 3D_Cubic doesn't work

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#143]
**Describe the bug**
Disabling RGB colors for a single layer still produces a colored image. Disabling RGB colors for all layers produces a partially colored image (see 2nd widget in screenshot)

**Indicate the dataset**
A single file from 0200 nm

**To Reproduce**
1. Load data
2. Click 3D_Cubic and click disable RGB colors

**Screenshots**
https://imgur.com/bZdBqni

**Comment by LemurPwned** [comment]
Yes, it is as it is expected
If the vectors are left by deafult, it works as no dot product is calculated.

For example, standard setup is : Rv [1 0 0], Gv [0 1 0], Bv[0 0 1]. 
This causes the x component R, y component G and z component B because it takes
(x dot Rv, y dot Gv, z dot Bv) to become a RGB tuple which in that very case simplifies to (x,y,z)
However, if RGB is disabled, then no dot product is calculated, so as a result only x, y and z compoents are counted as R, G, B components (as a default option).

**Comment by JakubChecinski** [comment]
Hmm, I don't like it. In my opinion, a user who disables RGB color expects one of the two things to happen: either assign the same color (e.g. black) to all pixels or switch the image to grayscale. If we cannot do that, I vote to remove this option altogether - in its current state it is confusing. 

And what about the second picture from screenshot? Why is it half black, half colored?

**Comment by LemurPwned** [comment]
Perhaps it should be renamed from "RGB disable" to "dot product disable"?

It is not black in the bottom but dark blue. The lower layers seem to have a different magnetisation orientation thus different coloring  than top level layers (that are vivid and colourful).

**Comment by JakubChecinski** [comment]
Maybe I don't understand the functionality of this feature - what are we trying to achieve here? If disabling dot product defaults to x->R, y->G, z->B, then how is that different from using [1,0,0], [0,1,0] and [0,0,1] vectors?

**Comment by LemurPwned** [comment]
It is not different in that particular case

**Comment by JakubChecinski** [comment]
Then I suggest to remove this tickbox or to replace it with a push button "Default" that will do the same thing and also reset the RGB vectors to [1,0,0], [0,1,0] and [0,0,1]. I believe it will be more transparent that way.
