### ISSUE TITLE
BetterWidget™ idea

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#32]
Idea is not to hardcode plugins inside code, and get rid of adding new if statements everywhere if new Widget is added to program, I think we should solve that by making some kind of file with all plugin names etc. and all files using them will be getting that data from some kind of interface(proxy/singleton) and using it dynamically. It's not needed for now but in future may be helpful.

**Comment by LemurPwned** [comment]
I will join this issue with #35 since it has conjugated issues

**Comment by pawelkulig1** [comment]
I think we should do something like that:
Every widget has at least two files, one is GUI class to configure it and another class is to show it as widget. If One adds new Widget (installs it by this script, all names are added to some file etc. ). It is from now shown in menu of Widgets (this list of widgets). If One choose widget, it shows configuration window with default configuration (user can change it), and after clicking OK, new widget will be added. This reduces problems with for ex. not selecting plot setting before animation. 
- First (if One enters program) One has to pick folder with data (everything else is locked).
- If One picks Widget he has to setup configuration, if not all options like (animation menu) is locked.

I think this kind of thinking will let us simplify app, and get rid of some complicated bugs.

**Comment by LemurPwned** [comment]
Ok, so what I am preparing right now is a Mediator with proxy that propagates settings from the GUI to itself, verifies it and then manages settings prompting and Canvas or GL object creation. This will not require any  blocking since settings are only prompted at creation and will be valid only for the object's lifetime (til deletion).

additionally, I will construct another class that will delegate Widget buildup (checks all files) and will enhance the namespace of the aforementioned settings mediator.

So for example:

- first enter the data (nothing can be set yet)
- pick a layout
- select widget
- (settings are prompted)
- widget is created if settings are valid
- close the widget if needed

I propose that settings should be valid for the whole lifetime of the 3d widget, if user wants to modify it, there is a need to reload it anyway so it wont save much time by modyfiying it i.e. delete and create new.
However, for now, settings Mediator will refresh modifications for 2D layers, that's ok.

**Comment by pawelkulig1** [comment]
Correct.
For now I will take care of:
- [ ] Button to delete widget.
- [ ] Improve idea with pop up when data is loading.
- [ ] Fix issue when some widgets are smaller and others bigger.
- [ ] I will refactor Worker code (Singleton which is triggering frame change).

**Comment by pawelkulig1** [comment]
We have to think about putting each Widget in separate directory (I don't think it's necessary), but for sure we must put all widgets in one directory.

**Comment by pawelkulig1** [comment]
To be clear this should also shorten main.py file because compose_dict will be inside widgetSettings class and choosingWidgetReceiver won't be made of cascade of is statements.

**Comment by LemurPwned** [comment]
Yes, that's exactly what I have started to do

**Comment by LemurPwned** [comment]
I think it was completely solved in #39 and #46
