### ISSUE TITLE
Recording video from app

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#51]
There is no option to record video right now, research need to be done, to find best fitting technology:
- [x] OpenCV - record video
- [x] QtGui.QPixmap.grabWindow() - convert slides to video
- [x] QWidget.grab() - previous is deprecated in Qt5.

**Comment by LemurPwned** [comment]
Yeah, forgot about this one, it was done in previous version and worked pretty well. It seems that recording has to be done as composition of frames (screenshots).

I can take it if you dont mind.

**Comment by pawelkulig1** [comment]
I wanted to improve previous solution, If you really want u can take that one. I will pick something else from to do list. Most important part is to do one issue at the time, to avoid messing things up.

**Comment by LemurPwned** [comment]
Sure, but I dont think this is much of the problem as long as you can keep track of your branches. Working on multiple issues is normal workflow- but we should limit ourselves to a single merge request per person - unlike I've done several days ago. Any other branches that have been completed during should be included in that pull request. How about that?

**Comment by pawelkulig1** [comment]
As far as I am concerned it's not proper way of dealing with bigger projects but ok, this may cause mess and it has negative impact on programmer performance. It's up to you.

**Comment by LemurPwned** [comment]
there are several issues connected to the proposed solutions:

- OpenCV
 is not an optimal solution, it is better to use scikitimage which has been tested to be faster and more reliable with less overhead.
- Instead of QWidget.grab() one could use glgrabFrameBuffer() which seems to be called anyway by QWidget.grab() as overriden method for QOpenGLWidget.
This is working functionally but it seems to require a current thread which is not always available to call: i.e
```python   
AbstractGLContext.py
...
 def set_i(self, value):
        self.i = value
        self.i %= self.iterations
        self.grabframeBuffer() <--- causes SIGABRT 
        self.update()
```
causes program to crash since in that context `set_i` is executed in a separate thread, so from OpenGL context function call comes from a different thread - thus an error. A typical solution could be to move OpenGL contexts into a separate thread, which has been tested by me and confirmed not to work because of the fact that Widgets in general are not allowed to run in a separate QThread.
Therefore, right now the frame buffer is called from within the OpenGL context. 

However, I must confirm whether it produces black (empty) screenshots because of empty framebuffers or it's just os-specific problem.

**Comment by LemurPwned** [comment]
It seems that this issue is strictly connected to Intel Graphics Cards, 
@pawelkulig1 can you confirm it if you have any other GPU at disposal?

**Comment by LemurPwned** [comment]
Don't need a confirmation, it is indeed Intel problem, however, I have managed to get i working on branch #62 . movies are composed provided ffmpeg is installed

- [ ] Add support for Windows if no ffmpeg is installed ? (if doable)
